
Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio Version 16
VisualStudioVersion = 16.0.31911.196
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Dockerfile", "Dockerfile\Dockerfile.csproj", "{BFE9C330-6DD9-4F73-A5EA-25410EA9C123}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{BFE9C330-6DD9-4F73-A5EA-25410EA9C123}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{BFE9C330-6DD9-4F73-A5EA-25410EA9C123}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{BFE9C330-6DD9-4F73-A5EA-25410EA9C123}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{BFE9C330-6DD9-4F73-A5EA-25410EA9C123}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
	GlobalSection(ExtensibilityGlobals) = postSolution
		SolutionGuid = {E2F218D1-B1BF-4700-A602-7F50A8300214}
	EndGlobalSection
EndGlobal
